<a href="https://colab.research.google.com/github/kaybrian/ML_/blob/main/00_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
## 00 pytorch Fundamentals
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


In [50]:

tensor_1 = torch.rand(2, 3)
tensor_2 = torch.rand(3, 2)

print("Tensor 1:")
print(tensor_1)
print("\nTensor 2:")
print(tensor_2)

Tensor 1:
tensor([[0.5176, 0.8001, 0.5927],
        [0.1624, 0.4820, 0.2028]])

Tensor 2:
tensor([[0.7273, 0.5568],
        [0.6295, 0.9293],
        [0.4202, 0.3223]])


In [51]:
tensor_1 @ tensor_2

tensor([[1.1291, 1.2228],
        [0.5067, 0.6037]])

In [52]:
tensor_1 = torch.tensor([
    [1, 2],
    [4, 5],
    [7, 8]])
tensor_2 = torch.tensor([
    [7, 2],
    [8, 5],
    [11,23]])



In [53]:
tensor_1

tensor([[1, 2],
        [4, 5],
        [7, 8]])

In [54]:
tensor_1.shape, tensor_2.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [55]:
# to fix the shape issues we can use transpose to change the dimensions of a tensor
tensor_2.T, tensor_2.T.shape

(tensor([[ 7,  8, 11],
         [ 2,  5, 23]]),
 torch.Size([2, 3]))

In [56]:
tensor_1.shape, tensor_2.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [57]:
torch.mm(tensor_1, tensor_2.T)

tensor([[ 11,  18,  57],
        [ 38,  57, 159],
        [ 65,  96, 261]])

In [58]:
# Tensor Aggregation methods
tensor_1.min()

tensor(1)

In [59]:
x = torch.arange(0,100,10)

In [60]:
x
x.dtype


torch.int64

In [61]:
torch.min(x)

tensor(0)

In [62]:
torch.max(x)

tensor(90)

In [63]:
# find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [64]:
# find the sum
torch.sum(x),  x.sum()

(tensor(450), tensor(450))

In [65]:
# finding the postional mean and max
torch.argmin(x)

tensor(0)

In [66]:
torch.argmax(x)

tensor(9)

In [67]:
x[0]

tensor(0)

In [68]:
x[9]

tensor(90)

In [69]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes the input tensor to a defined shape
* View - return the view tensor of the input tensor
* stacking
* Squeezing
* Unsqueezing
* Permute



In [70]:
# create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [71]:
# reshaping a tensor  # addinng Dimensions to the shapes and tensors
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [72]:
# add 2 dimenisons
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [73]:
# add 2 dimenisions
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [74]:
# change the View of the tensors
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [75]:
# changing  CHanges the x (view of a tensor shares the same memory as the orginal one)

In [76]:
# stacking the tensors on each other

x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [77]:
# using Squeeze in the target tensor
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [78]:
x_reshaped.squeeze(),x_reshaped.squeeze().shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [79]:
x_reshaped.unsqueeze(dim=0),x_reshaped.unsqueeze(dim=0).shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.Size([1, 3, 3]))

In [80]:
x_reshaped.shape

torch.Size([3, 3])

 Permuteing the Tensor  

 - Rearranges the Dimensions of the Tensor


In [81]:
x = torch.randn(2, 3, 5)
x.size()



torch.Size([2, 3, 5])

In [82]:
torch.permute(x, (2, 0, 1)).size()

torch.Size([5, 2, 3])

In [84]:
# indexing in Tensors
x = torch.randn(3, 4)
x


tensor([[ 0.4283,  0.6245,  1.0165, -1.1415],
        [ 0.0046, -0.0204, -0.1181, -0.8949],
        [ 0.7342,  0.9124, -1.3566,  0.2996]])

In [85]:
indices = torch.tensor([0, 2])


In [86]:
torch.index_select(x, 0, indices)


tensor([[ 0.4283,  0.6245,  1.0165, -1.1415],
        [ 0.7342,  0.9124, -1.3566,  0.2996]])

In [87]:
torch.index_select(x, 1, indices)

tensor([[ 0.4283,  1.0165],
        [ 0.0046, -0.1181],
        [ 0.7342, -1.3566]])

In [91]:
x[2][3]

tensor(0.2996)

In [93]:
# get all values of the 0th and 1st dimensions but only index 1 of the 2 dimenisons

x[:, 1]

tensor([ 0.6245, -0.0204,  0.9124])

In [94]:
x.shape

torch.Size([3, 4])

# Pytorch and Numpy


* Data in numpy array, want them in Pytorch Tensor -> torch.from_numpy(ndarry)
* Pytorch Tensor -> Numpy =-> torch.numpy()


In [95]:
import numpy as np

In [100]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) # by defualt, it brings out the default float64, so you need to make it float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [101]:
array = array + 1

In [103]:
array,  tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [104]:
# Tensor to Numpy array
tensor = torch.ones(7)

numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [105]:
# change the tensor to the arry
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))


## Reproducbility (trying to take random out of Random)

`start with random numbers -> tensor operations -> update random numbers to try to make she operations of the date -> again -> again ...

To reduce the randomnese in neural networks and pytorch comes the concept of the random seed



In [106]:
torch.rand(3,3)

tensor([[0.7354, 0.6828, 0.1768],
        [0.7168, 0.2755, 0.8050],
        [0.0409, 0.1953, 0.4184]])

In [107]:
torch.rand(3,3)

tensor([[0.6280, 0.2944, 0.0659],
        [0.5162, 0.1675, 0.3359],
        [0.5822, 0.9603, 0.8940]])

In [112]:
# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5639, 0.0382, 0.2874, 0.0401],
        [0.6657, 0.5896, 0.6256, 0.1062],
        [0.9000, 0.9236, 0.0631, 0.0534]])
tensor([[0.4871, 0.2003, 0.0778, 0.7817],
        [0.0907, 0.3911, 0.3342, 0.6393],
        [0.1455, 0.1698, 0.6337, 0.1576]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [114]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
## running tensors and pytorch opjects on GPUs and faster computations on numbers

'''
  - make the process faster and easier for producing and working on numbers
'''