<a href="https://colab.research.google.com/github/kaybrian/ML_/blob/main/Naive_Bayes_Classifier_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
data = pd.read_csv('/content/titanic.csv')

In [3]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df = data.drop(['PassengerId','Name','SibSp','Parch', 'Ticket','Cabin','Embarked'],axis=1)

In [5]:
df

Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [6]:
#  drop the NaN fields in age
df = df.dropna()

In [7]:
# encode the sex columns to numebers
df['Sex'] = df['Sex'].map({'male':0,'female':1})

<ipython-input-7-8deb56717f7e>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sex'] = df['Sex'].map({'male':0,'female':1})


In [8]:
df

Survived  Pclass  Sex   Age     Fare
0           0       3    0  22.0   7.2500
1           1       1    1  38.0  71.2833
2           1       3    1  26.0   7.9250
3           1       1    1  35.0  53.1000
4           0       3    0  35.0   8.0500
..        ...     ...  ...   ...      ...
885         0       3    1  39.0  29.1250
886         0       2    0  27.0  13.0000
887         1       1    1  19.0  30.0000
889         1       1    0  26.0  30.0000
890         0       3    0  32.0   7.7500

[714 rows x 5 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  714 non-null    int64  
 1   Pclass    714 non-null    int64  
 2   Sex       714 non-null    int64  
 3   Age       714 non-null    float64
 4   Fare      714 non-null    float64
dtypes: float64(2), int64(3)
memory usage: 33.5 KB


In [11]:
# split the data in to the train and slipt
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('Survived',axis=1),
                                                    df['Survived'],test_size=0.30,
                                                    random_state=101)


In [12]:
len(X_train)

499

In [13]:
len(X_test)

215

In [14]:
# build the naive bayes model
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
model = GaussianNB()

In [15]:
model.fit(X_train,y_train)

GaussianNB()

In [17]:
# measure the score
model.score(X_test,y_test)

0.7627906976744186

In [18]:
y_test

853    1
540    1
259    1
690    1
469    1
      ..
876    0
216    1
433    0
183    1
889    1
Name: Survived, Length: 215, dtype: int64

In [19]:
model.predict(X_test)

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
model.predict(X_test)[:10]

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 0])

In [21]:
y_test[:10]

853    1
540    1
259    1
690    1
469    1
870    0
57     0
707    1
448    1
293    0
Name: Survived, dtype: int64

In [22]:
model.predict_proba(X_test)

array([[7.72334768e-02, 9.22766523e-01],
       [2.50688041e-02, 9.74931196e-01],
       [3.61114601e-01, 6.38885399e-01],
       [6.04627510e-01, 3.95372490e-01],
       [4.12262267e-01, 5.87737733e-01],
       [9.69576677e-01, 3.04233229e-02],
       [9.70386393e-01, 2.96136074e-02],
       [8.11931162e-01, 1.88068838e-01],
       [4.38137758e-01, 5.61862242e-01],
       [5.24430771e-01, 4.75569229e-01],
       [2.96119229e-01, 7.03880771e-01],
       [9.65483827e-01, 3.45161735e-02],
       [9.66136621e-01, 3.38633795e-02],
       [1.71835151e-02, 9.82816485e-01],
       [3.18924191e-01, 6.81075809e-01],
       [5.72156805e-01, 4.27843195e-01],
       [9.73231688e-01, 2.67683119e-02],
       [2.43545838e-17, 1.00000000e+00],
       [9.70399554e-01, 2.96004456e-02],
       [3.60537841e-02, 9.63946216e-01],
       [9.71816802e-01, 2.81831981e-02],
       [9.71768861e-01, 2.82311388e-02],
       [7.92257317e-01, 2.07742683e-01],
       [2.27297427e-06, 9.99997727e-01],
       [9.575133