<a href="https://colab.research.google.com/github/kaybrian/ML_/blob/main/Naive_Bayes_Classifier_Algorithm_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
data = pd.read_csv('/content/spam.csv')

In [3]:
data.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
data.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [5]:
# convert the catergory into 1 and 0
data['spam'] = data['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [6]:
data.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
# get the train test splits
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data['Message'], data['spam'], test_size=0.25, random_state=101)

In [8]:
# change the message into numbers
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X_train_count = cv.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [9]:
#  using multinomialNB
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count, y_train)

MultinomialNB()

In [10]:
# get tow emails
email = [
    'Hey Brian, how are you doing today?, can we get some time to watch a match together tomorrow? ',
    'upto 20% discount on your first order, exclusive offers for you. Dont miss this reward!'
]

# make a prediction for the emails
email_count = cv.transform(email)
model.predict(email_count)

array([0, 1])

In [11]:
#  make a prediction and score of the model
X_test_count = cv.transform(X_test)
model.score(X_test_count, y_test)

0.9842067480258435

In [12]:
# using the sklearn pipeline
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

# fit the model
clf.fit(X_train, y_train)

# make the prediction
clf.predict(email)


array([0, 1])

In [13]:
# get the perfromace of the classifier
from sklearn.metrics import classification_report
print(classification_report(y_test, clf.predict(X_test)))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1227
           1       0.99      0.88      0.93       166

    accuracy                           0.98      1393
   macro avg       0.99      0.94      0.96      1393
weighted avg       0.98      0.98      0.98      1393

